### PR TITLE
Code Refactor 

### PR DESCRIPTION
**Pull request by newtonMM**
Code refactor Carousels Section to Clear white Space on Mobile and deletion of Images that took too much space

### CODE REVIEW

**Review by denomash — COMMENTED** [review]
@newtonMM Why are you overriding Talwind classes in `src/assets/css/main.css`. It beats the reason to use Talwind in the first place

In the future it's better to add your own custom classes on top of Talwind instead of overriding the existing ones.

**Comment by newtonMM** [comment]
@denomash on the installation of tailwind this was the way I configured my tailwind flow to work, CSS would be generated by tailwind to my main.css, unless am doing it wrong

**Comment by denomash** [comment]
@newtonMM Tailwind doesn’t normally need much configuration as you have done. This is the best way to set up 👉 https://tailwindcss.com/docs/guides/create-react-app

Maybe you can create another PR after this to update configuration since this one has a lot of changes

**Comment by denomash** [comment]
@newtonMM  I looked at the UI and maybe there are a few things you can improve:

1. The contact us button is distorted and redirects wrongly 👇 
Screenshot 2022-05-14 at 21 35 58

2. You can add some padding on each of these three components(and the ones above) they would look much better.
image

**Pull request merged**
